name: "Auto Release"
author: "Orell Bühler"
description: "Create a versioned release with a changelog from your commits"
inputs:
  token:
    description: "GitHub token with access to this repository"
    required: true
  target:
    description: "Target branch of the action, used to determine which is the next version"
    required: true
  with-description:
    description: "When set adds the body of the commit to the changelog"
    required: false
    default: false
  minor-branch:
    description: "Target branch which increases the minor version"
    required: true
  patch-branch:
    description: "Target branch which increaes the patch version"
    required: true
  major-branch:
    description: "Target branch which increases the major version"
    required: false
    default: null
runs:
  using: "node16"
  main: "dist/index.js"
